# Generated by Django 5.0.1 on 2025-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='schema_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
